### ISSUE TITLE
Click on button to delete account does nothing

### ISSUE THREAD

**Issue by cloacker** [mageplaza/magento-2-gdpr#10]
Greetings,

Magento 2.3.0
Mageplaza GDPR 1.2.3

When a users clicks on the button with the delete account action, nothing happens.

**Comment by Desmond-Mageplaza** [comment]
Hi @cloacker,

Sorry for the late response.

Did you check the console?
There may be some errors in with the JS which handle this kind of action so if you could provide the console error, it would be very helpful

**Comment by Desmond-Mageplaza** [comment]
This issue is closed due to inactivity for a while.
You can reopen the issue if the problem still persists.
Thanks.

**Comment by erikhansen** [comment]
We are also experiencing this on Magento 2.3.4-p2 Commerce. 

The `address` require JS mapping is never run: https://github.com/mageplaza/magento-2-gdpr/blob/2.4/view/frontend/templates/account/edit/delete.phtml#L44

I think the reason for this is that the `mageplaza/module-gdpr` extension does not include a `requirejs-config.js` file, nor does it include any JS in `vendor/mageplaza/module-gdpr/view/frontend/web/js`. I'm guessing all of that is contained in the Pro version of the extension.

**Comment by dcbaldwin1** [comment]
> We are also experiencing this on Magento 2.3.4-p2 Commerce.
> 
> The `address` require JS mapping is never run: https://github.com/mageplaza/magento-2-gdpr/blob/2.4/view/frontend/templates/account/edit/delete.phtml#L44
> 
> I think the reason for this is that the `mageplaza/module-gdpr` extension does not include a `requirejs-config.js` file, nor does it include any JS in `vendor/mageplaza/module-gdpr/view/frontend/web/js`. I'm guessing all of that is contained in the Pro version of the extension.

In delete.phtml, the alias it's calling is default magento address.js at vendor/magento/module-customer/view/frontend/web/js/address.js.  It's kind of confusing but even when deleting an account, it utilizes this js file to send the request to the account delete controller.
