### ISSUE TITLE
GPDRPRO ERROR

### ISSUE THREAD

**Issue by dtavieres** [mageplaza/magento-2-gdpr#11]
CSV / XLS files not downloading.  Safari network error , chrome File type mismatch and Firefox not present.  Any help is welcomed. 
Thank you

**Comment by bdtrung** [comment]
We're checking and will notify you when we found any solution.

**Comment by bdtrung** [comment]
We've checked this as your describe, but we saw it working normally.
Please try to upgrade the latest version of our module and try again.
Thanks!

**Comment by bdtrung** [comment]
Close due to no response in 7 days.
