### ISSUE TITLE
magento 2.2.8 install/build error

### ISSUE THREAD

**Issue by jfgalano** [mageplaza/magento-2-gdpr#8]
1) build magento
2) error when downloading mageplaza/module-gdpr module

W:   - Installing mageplaza/module-gdpr (1.2.1): Downloading
        W:                                                                                                                                                      
        W:   [Composer\Downloader\TransportException]                                                                                                           
        W:   The 'https://repo.magento.com/archives/mageplaza/module-gdpr/mageplaza-module-gdpr-1.2.1.0.zip' URL could not be accessed: HTTP/1.1 403 Forbidden  
        W:                                                                                                                                                      
        W: 
        W: install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
        W: 
      
      E: Error building project: `composer` could not be run. Aborted build.

    E: Error: Unable to build application, aborting.

**Comment by Arthas7895** [comment]
You can install the module manually by downloading it directly(https://prnt.sc/pqx3aw) and adding it at the directory || app/code/Mageplaza/Gdpr (https://prnt.sc/pqx4gt).
Then you can run the upgrade and deploy commands

**Comment by Arthas7895** [comment]
It's been over 7 days and I haven't received your response, I'll close the issue here
Thank you!
